<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Click to see screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Mon_May_13_16_50_17_EDT_2019.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Mon_May_13_16_50_17_EDT_2019.jpg><img src=Mon_May_13_16_50_17_EDT_2019.jpg height=200 width=200</img></a>]]>
    </line>
    <line>
      <![CDATA[Click to see screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Mon_May_13_16_50_34_EDT_2019.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Mon_May_13_16_50_34_EDT_2019.jpg><img src=Mon_May_13_16_50_34_EDT_2019.jpg height=200 width=200</img></a>]]>
    </line>
  </reporter-output>
  <suite name="Page Object Model" duration-ms="20312" started-at="2019-05-13T20:50:14Z" finished-at="2019-05-13T20:50:34Z">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="3586" started-at="2019-05-13T20:50:14Z" finished-at="2019-05-13T20:50:17Z">
      <class name="com.frankbahar.testcases.LoginTest">
        <test-method status="FAIL" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.frankbahar.testcases.LoginTest@5674e1f2]" name="loginTest" duration-ms="1103" started-at="2019-05-13T16:50:14Z" data-provider="dp" finished-at="2019-05-13T16:50:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Selenium@123, runmode=Y, username=fikretbahar@yahoo.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login test failed
	at org.testng.Assert.fail(Assert.java:93)
	at com.frankbahar.testcases.LoginTest.loginTest(LoginTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Mon_May_13_16_50_17_EDT_2019.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Mon_May_13_16_50_17_EDT_2019.jpg><img src=Mon_May_13_16_50_17_EDT_2019.jpg height=200 width=200</img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.frankbahar.testcases.LoginTest -->
    </test> <!-- Login Test -->
    <test name="Create Account Test" duration-ms="5374" started-at="2019-05-13T20:50:28Z" finished-at="2019-05-13T20:50:34Z">
      <class name="com.frankbahar.testcases.CreateAccountTest">
        <test-method status="FAIL" signature="createAccountTest(java.util.Hashtable)[pri:0, instance:com.frankbahar.testcases.CreateAccountTest@6986bbaf]" name="createAccountTest" duration-ms="4943" started-at="2019-05-13T16:50:28Z" data-provider="dp" finished-at="2019-05-13T16:50:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{accountname=Frank}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Create Account Test Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Create Account Test Failed
	at org.testng.Assert.fail(Assert.java:93)
	at com.frankbahar.testcases.CreateAccountTest.createAccountTest(CreateAccountTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Mon_May_13_16_50_34_EDT_2019.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Mon_May_13_16_50_34_EDT_2019.jpg><img src=Mon_May_13_16_50_34_EDT_2019.jpg height=200 width=200</img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- createAccountTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.frankbahar.testcases.CreateAccountTest@6986bbaf]" name="tearDown" is-config="true" duration-ms="843" started-at="2019-05-13T16:50:45Z" finished-at="2019-05-13T16:50:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.frankbahar.testcases.CreateAccountTest -->
    </test> <!-- Create Account Test -->
  </suite> <!-- Page Object Model -->
</testng-results>
